arb-dir: l10n
template-arb-file: game_articles_en.arb
output-localization-file: game_articles_localizations.dart
output-class: GameArticlesLocalizations
output-dir: lib/l10n
required-resource-attributes: false
