arb-dir: l10n
template-arb-file: game_memory_en.arb
output-localization-file: game_memory_localizations.dart
output-class: GameMemoryLocalizations
output-dir: lib/l10n
required-resource-attributes: false
